version: "3"
services:

  mongors1n1:
    image: mongo:${MONGO_VERSION}
    command: mongod --noprealloc --smallfiles --replSet mongors1 --shardsvr --oplogSize 16 --noauth --bind_ip_all
    environment:
      TERM: xterm
    expose:
      - 27018

  mongors1n2:
    image: mongo:${MONGO_VERSION}
    command: mongod --noprealloc --smallfiles --replSet mongors1 --shardsvr --oplogSize 16 --noauth --bind_ip_all
    environment:
      TERM: xterm
    expose:
      - 27018

  mongors1n3:
    image: mongo:${MONGO_VERSION}
    command: mongod --noprealloc --smallfiles --replSet mongors1 --shardsvr --oplogSize 16 --noauth --bind_ip_all
    environment:
      TERM: xterm
    expose:
      - 27018

  mongors2n1:
    image: mongo:${MONGO_VERSION}
    command: mongod --noprealloc --smallfiles --replSet mongors2 --shardsvr --oplogSize 16 --noauth --bind_ip_all
    environment:
      TERM: xterm
    expose:
      - 27018

  mongors2n2:
    image: mongo:${MONGO_VERSION}
    command: mongod --noprealloc --smallfiles --replSet mongors2 --shardsvr --oplogSize 16 --noauth --bind_ip_all
    environment:
      TERM: xterm
    expose:
      - 27018

  mongors2n3:
    image: mongo:${MONGO_VERSION}
    command: mongod --noprealloc --smallfiles --replSet mongors2 --shardsvr --oplogSize 16 --noauth --bind_ip_all
    environment:
      TERM: xterm
    expose:
      - 27018

  mongocfg1:
    image: mongo:${MONGO_VERSION}
    command: mongod --noprealloc --smallfiles --configsvr --replSet mongocfg1 --noauth --bind_ip_all
    environment:
      TERM: xterm
    expose:
      - 27019

  mongocfg2:
    image: mongo:${MONGO_VERSION}
    command: mongod --noprealloc --smallfiles --configsvr --replSet mongocfg1 --noauth --bind_ip_all
    environment:
      TERM: xterm
    expose:
      - 27019

  mongocfg3:
    image: mongo:${MONGO_VERSION}
    command: mongod --noprealloc --smallfiles --configsvr --replSet mongocfg1 --noauth --bind_ip_all
    environment:
      TERM: xterm
    expose:
      - 27019

  mongos1:
    image: mongo:${MONGO_VERSION}
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
    command: mongos --configdb mongocfg1/mongocfg1:27019,mongocfg2:27019,mongocfg3:27019 --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - .:/tmp

  mongos2:
    image: mongo:${MONGO_VERSION}
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
    command: mongos --configdb mongocfg1/mongocfg1:27019,mongocfg2:27019,mongocfg3:27019 --bind_ip_all
    ports:
      - 27018:27017